### ISSUE TITLE
Docker image for development

### ISSUE THREAD

**Issue by caronzh03** [microsoft/VPTQ#111]
Hi, are there plans to create a docker image for development / testing, especially for the `algorithm` branch where one might have needs to quantize a customized LLM.

**Comment by YangWang92** [comment]
We currently do not have Docker images. If you are looking to develop using a Docker image, you should base it on NVIDIA Docker. 

Currently, you can start by creating a conda environment using the algo-environment.yml, which should meet your needs. I may add a Dockerfile in the future, but that will take some time.

**Comment by caronzh03** [comment]
Thanks @YangWang92 for the pointers.
I followed your suggestion, and used Nvidia's docker image `nvcr.io/nvidia/cuda:12.1.0-runtime-ubuntu20.04`, but during the CUDA compilation step (`TORCH_CUDA_ARCH_LIST=8.0 pip install -e . --no-build-isolation`), I got the following error:
```
      In file included from /root/miniconda3/envs/vptq-algo/lib/python3.10/site-packages/torch/include/ATen/cuda/CUDAContext.h:3,
                       from /models/VPTQ/csrc/common.h:5,
                       from /models/VPTQ/csrc/ops.cc:5:
      /root/miniconda3/envs/vptq-algo/lib/python3.10/site-packages/torch/include/ATen/cuda/CUDAContextLight.h:6:10: fatal error: cuda_runtime_api.h: No such file or dire
ctory
          6 | #include <cuda_runtime_api.h>
            |          ^~~~~~~~~~~~~~~~~~~~
      compilation terminated.
```

After some googling, I'm guessing it's because CUDA installation cannot be found by the compiler. I've tried several things, including manually set the `CUDA_HOME`, etc, but still no luck in getting it working.

Did you develop on a Ubuntu box?

**Comment by caronzh03** [comment]
NVM, the above issue was fixed by:
1. Changing the Docker image to `12.1.0-devel-ubuntu22.04`
2. Setting the CUDA home: `export CUDA_HOME=/usr/local/cuda-12.1`

**Comment by YangWang92** [comment]
> NVM, the above issue was fixed by:
> 
> 1. Changing the Docker image to `12.1.0-devel-ubuntu22.04`
> 2. Setting the CUDA home: `export CUDA_HOME=/usr/local/cuda-12.1`
Hi @caronzh03,
Thanks for your help. Yes, this error occurs because `nvcc` cannot find the corresponding CUDA library and header files during compilation. On Ubuntu 20.04, you can also make nvcc find the library by setting export CUDA_HOME=/usr/local/cuda-12.1 or export PATH=/usr/local/cuda-12/bin/:$PATH. 

If convenient, could you please submit a simple pull request and modify the line at https://github.com/microsoft/VPTQ?tab=readme-ov-file#build-from-source? I will merge it immediately, and you can appear as a contributor to the project here: https://github.com/microsoft/VPTQ/graphs/contributors. 

If it's not convenient for you, I can make the fix.

**Comment by caronzh03** [comment]
@YangWang92 https://github.com/microsoft/VPTQ/pull/112 :)

**Comment by YangWang92** [comment]
> [@YangWang92](https://github.com/YangWang92) [#112](https://github.com/microsoft/VPTQ/pull/112) :)

Thanks!
