### ISSUE TITLE
where are the layer-wise fine-tune codes in algorithm branch?

### ISSUE THREAD

**Issue by Huangdequ** [microsoft/VPTQ#132]
In section 4, you suggest to perform layer-wise fine-tune after perform vptq stage, but I cannot find any code in algorithm branch.

**Comment by YangWang92** [comment]
Yes, in the paper, we included layer-wise fine-tuning. However, we recently found that running end-to-end fine-tuning performs better than layer-wise fine-tuning. I removed the code for layer-wise fine-tuning because it requires collecting a large amount of layer-wise input and output data, which is less convenient compared to end-to-end training.
