### ISSUE TITLE
about permutation and quant channel

### ISSUE THREAD

**Issue by laomao0** [microsoft/VPTQ#87]
Hi, I see 'enable_perm' in the 'vqlinear.py', is it means to reorder the input channel of the weight?
And I see the 'enable_perm' can be removed  [link](https://github.com/ggerganov/llama.cpp/discussions/9974#discussioncomment-11027488).

Are there some specific numbers, such as ppl / acc, about do or not do weight permutaion?

Another question about the quant dim, i see the code is 'out channel' style, the scale is equal to the in channel dim.
For example, X * W, X is activattion with shape MxK, W is weight with shape KxN，it seems vptq quant weight in N dim,
not in 'inner dimension', i.e., the 'K' dim. 

Is there any efficiency problem using this quant dim with MatMul?

Thanks.
![Image](https://github.com/user-attachments/assets/e2002095-0e74-40a5-97cf-23b5a16930ce)

**Comment by YangWang92** [comment]
Our current version allows permutation, similar to the principle in GPTQ. We first quantize the channels that are more prone to quantization errors (with larger values in diag(hessian)). Of course, this option can be disabled. I don’t quite remember the exact impact of permutation on PPL, but you can try it once I release the algorithm.

**Comment by YangWang92** [comment]
![Image](https://github.com/user-attachments/assets/aad5fa3c-8a50-42bb-8687-f8d33fa6253e)
![Image](https://github.com/user-attachments/assets/0ec599eb-3bfb-49ca-9701-6530399c3d87)

The fundamental reason we choose the output dimension is that the quantization dimension aligns with the dimension used in GPTQ's solution. This allows us to quantize one column of data with a single vector, rather than quantizing vv columns of data at once. AQLM/GPTVQ, on the other hand, choose the input dimension, which forces them to quantize vv columns at once, resulting in significant accumulated errors. Moreover, GPTVQ cannot use a larger vector length. This approach is primarily for accuracy rather than inference speed.
